set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g history-limit 50000
setw -q -g utf8 on
set -s set-clipboard external
set -g allow-passthrough on
set -g terminal-features 'xterm*:clipboard'
set -g window-size latest
setw -g aggressive-resize on
